version: '3'

services:

    app:
        build: .
        container_name: xdebug-app
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=code_micro_videos
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
            # XDEBUG 2
            #- XDEBUG_CONFIG=remote_host=app remote_port=9001 remote_enable=1 remote_autostart=1 remote_handler=dbgp remote_log=/var/log/xdebug.log
            - XDEBUG_CONFIG=discover_client_host=true client_host=app client_port=9003 start_with_request=yes log=/var/log/xdebug.log
            - XDEBUG_MODE=debug
            - XDEBUG_SESSION=vscode
        ports:
            - "9003:9003"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: xdebug-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: xdebug-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: xdebug-redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
